# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PRATIK SHAH
email: pratik.t.shah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# social media links
twitter_username: pratikshah
github_username:  pratikmshah
linkedin_username: pratikmshah
instagram_username: pratikshah_
aboutme: "https://about.me/pratikshah"

# project links
prism-demo: "http://prism-dbc.herokuapp.com/"
prism-src: "https://github.com/pratikmshah/prism"
idunno-demo: "/projects/iDunno/index.html"
idunno-src: "https://github.com/pratikmshah/iDunno"

# about me links
resume: "https://resume.creddle.io/resume/f4o552ugu6v"

# Build settings
markdown: kramdown

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: programming
      permalink: /blog/:categories/:title
      layout: "post"
      comments: true